ground_segmentation/ground_segmentation:
  ros__parameters:
    RNR_intensity_thr: 2.0
    RNR_ver_angle_thr: -15.0
    adaptive_seed_selection_margin: -1.2
    cloud_topic: "/point_cloud_fuser/fused_point_cloud"
    frame_id: "map"
    czm:
      elevation_thresholds:
      - 0
      - 0
      - 0
      - 0
      flatness_thresholds:
      - 0
      - 0
      - 0
      - 0
      mum_rings_each_zone:
      - 1
      - 1
      - 1
      - 1
      num_sectors_each_zone:
      - 8
      - 12
      - 16
      - 24
      num_zones: 4
    enable_RNR: true
    enable_RVPF: true
    enable_TGR: true
    max_r: 15
    min_r: 0.6
    mode: czm
    num_iter: 3
    num_lpr: 20
    num_min_pts: 10
    save_flag: true
    sensor_height: 1.99
    th_dist: 0.175
    th_dist_v: 0.1
    th_seeds: 0.3
    th_seeds_v: 0.25
    uprightness_thr: 0.707
    verbose: false
    visualize: false
